version: "3.9"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # <-- allow empty
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: "%"                # <-- allow root from phpMyAdmin container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "--password="]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5-apache
    environment:
      PMA_HOST: db
      # Don’t set PMA_USER / PMA_PASSWORD so you can type root with blank password
    ports:
      - "8080:80"
    depends_on:
      - db

  next:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: